<div id="dialog-reboot-confirm" title="Reboot durchführen" style="display:none">
	<form id="reboot-confirm">
	<br>
	<span class="ui-icon ui-icon-alert" style="float:left; margin-right:3em;"></span>
	<span id="dialog-reboot-msg"></span>
	</form>
</div>

<div id="dialog-update-confirm" title="Updates installieren" style="display:none">
	<form id="update-confirm">
	<br>
	<span class="ui-icon ui-icon-alert" style="float:left; margin-right:3em;"></span>
	<span id="dialog-update-msg"></span>
	</form>
</div>
