---
- name: Nupama Roles Playbook
  vars_prompt:
    - name: nupama_target
      prompt: Zielhost
      private: false
  vars:
    nupama_roles: >
      {{ query('lines',
      'python3 /build/nupama/backend/nupamabackend.py listroles '
      + nupama_target) }}
  hosts: "{{ nupama_target }}"
  tasks:
    - name: Configured Roles
      debug:
        msg: "{{ nupama_roles }}"
    - name: Include Roles
      include_role:
        name: "{{ item }}"
      loop: "{{ nupama_roles }}"
