<div id="dialog-update-confirm" title="Repo aktualisieren" style="display:none">
	<form id="update-confirm">
	<br>
	<span class="ui-icon ui-icon-alert" style="float:left; margin-right:3em;"></span>
	<span id="dialog-update-msg"></span>
	</form>
</div>

<div id="dialog-mirror-confirm" title="Repo spiegeln" style="display:none">
	<form id="mirror-confirm">
	<br>
	<span class="ui-icon ui-icon-alert" style="float:left; margin-right:3em;"></span>
	<span id="dialog-mirror-msg"></span>
	</form>
</div>
